In [2]:
import numpy as np


In [5]:
s=np.zeros([3,3]
          )

In [6]:
s

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [11]:
s=range(1,10)

In [18]:
s=np.asarray(s,dtype=np.int16)

In [19]:
s=s.reshape(3,3)


In [29]:
np.linalg.svd(s)

(array([[-0.21483724,  0.88723069,  0.40824829],
        [-0.52058739,  0.24964395, -0.81649658],
        [-0.82633754, -0.38794278,  0.40824829]]),
 array([  1.68481034e+01,   1.06836951e+00,   4.41842475e-16]),
 array([[-0.47967118, -0.57236779, -0.66506441],
        [-0.77669099, -0.07568647,  0.62531805],
        [-0.40824829,  0.81649658, -0.40824829]]))

In [30]:
s=[[2,1],[0,-1]]

In [35]:

a,b=np.linalg.eig(s)

In [36]:
a


array([ 2., -1.])

In [48]:
invb= np.linalg.inv(b.transpose())

In [49]:
invb

array([[ 1.        ,  0.        ],
       [ 0.33333333,  1.05409255]])

In [55]:
m=np.dot(b.transpose(),np.diag(a))

In [44]:
s

[[2, 1], [0, -1]]

In [56]:
np.dot(m,invb)

array([[ 4.        ,  0.        ],
       [-0.66491106,  0.9       ]])

In [75]:
a, eigvecs = np.linalg.eig(s)


In [76]:
np.diag(a)

array([[ 2.,  0.],
       [ 0., -1.]])

In [98]:
p=eigvecs

In [102]:
pd=np.dot(p,pow(np.diag(a),10))

In [103]:
np.dot(pd,np.linalg.inv(p))

array([[  1.02400000e+03,   3.41000000e+02],
       [  0.00000000e+00,   1.00000000e+00]])

In [101]:
np.asarray(s)

array([[ 2,  1],
       [ 0, -1]])

In [110]:
import math
math.cos(np.pi*30/180)

0.8660254037844387

In [112]:
math.sqrt(3)/2

0.8660254037844386

In [136]:
from numpy import cross, eye, dot
from scipy.linalg import expm3, norm

def M(axis, theta):
    return expm3(cross(eye(3), axis/norm(axis)*theta))

v, axis, theta = [0,0,1], [0,0,1], np.pi/60.0
M0 = M(axis, theta)
print cross(eye(3),axis/norm(axis)*theta)
print(dot(M0,v))

[[ 0.         -0.05235988  0.        ]
 [ 0.05235988  0.          0.        ]
 [ 0.          0.          0.        ]]
[ 0.  0.  1.]


In [132]:
#cross(eye(2),norm([1,1]))
eye(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [139]:
import scipy.ndimage.interpolation as pl


In [153]:
def rotation(deg):
    r=np.ones([2,2])
    r[0,0]=np.cos(np.radians(deg))
    r[0,1]=-1*np.sin(np.radians(deg))
    r[1,0]=np.sin(np.radians(deg))
    r[1,1]=np.cos(np.radians(deg))
    return r

In [154]:
s=rotation(30)

In [158]:
np.dot([[1,0],[0,-1]],s)

array([[ 0.8660254, -0.5      ],
       [-0.5      , -0.8660254]])

In [146]:
P=np.asarray([[0,1/3.0,1/3.0],[.5,0,2.0/3.0],[0.5,2.0/3.0,0]])
I=np.eye(P.shape[0])
b=np.zeros(P.shape[0])
m=P-I
np.linalg.eig(m)

(array([-1.33333333,  0.        , -1.66666667]),
 array([[ -8.16496581e-01,   4.26401433e-01,  -1.88411095e-16],
        [  4.08248290e-01,   6.39602149e-01,  -7.07106781e-01],
        [  4.08248290e-01,   6.39602149e-01,   7.07106781e-01]]))

In [57]:
m

array([[-0.029,  0.145,  0.   ],
       [ 0.029, -0.228,  0.508],
       [ 0.   ,  0.077, -0.508]])

In [9]:
import sympy

In [159]:
print sympy.Matrix(np.vstack(((P-I).transpose(),b.transpose())).transpose()).rref()

(Matrix([
[1.0,   0,   0, 0],
[  0, 1.0,   0, 0],
[  0,   0, 1.0, 0]]), [0, 1, 2])


In [41]:

np.vstack(((P-I).transpose(),b.transpose())).transpose()

array([[-0.029,  0.145,  0.   ,  0.   ],
       [ 0.029, -0.228,  0.508,  0.   ],
       [ 0.   ,  0.077, -0.508,  0.   ]])

In [21]:
P-I

array([[-0.029,  0.145,  0.   ],
       [ 0.029, -0.228,  0.508],
       [ 0.   ,  0.077, -0.508]])

In [156]:
print sympy.Matrix(P-I).LUdecomposition()

(Matrix([
[   1,    0, 0],
[-0.5,    1, 0],
[-0.5, -1.0, 1]]), Matrix([
[-1.0,  0.333333333333333,     0.333333333333333],
[   0, -0.833333333333333,     0.833333333333333],
[   0,                  0, -2.22044604925031e-16]]), [])


In [68]:
from scipy import linalg as LA


a,d,c=LA.eig(P-I, left=True)


In [72]:
idx = np.argsort(a)[::-1]

In [73]:
v=a[idx,]

In [120]:
c[2]

array([ 0.02883086,  0.13876687,  0.58403112])

In [216]:
sstate = np.linalg.eig(P)[1][1,:]
np.linalg.eig(P-I)[0]

array([-1.33333333,  0.        , -1.66666667])

In [220]:

sstate =np.linalg.eig(P-I)[1][-1,:]
sstate=sstate/sstate.sum()
sstate

array([ 0.23262578,  0.36445455,  0.40291967])

In [222]:
np.dot(sstate,P)

array([ 0.38368711,  0.34615504,  0.32051163])

In [145]:
sstate

array([ 0.98138906, -0.75470682,  0.19596574])

In [153]:
np.linalg.eig(P-I)[0]

array([-1.33333333,  0.        , -1.66666667])

In [160]:
 np.linalg.solve(P-I, b)

array([ 0.,  0.,  0.])

In [247]:

def solven(A):
    u, s, vh = np.linalg.svd(A)
    #print u,s,vh
    eps=s.min()
    null_mask = (s <= eps)
    #print null_mask
    null_space = np.compress(null_mask, vh, axis=0)
    #print null_space
    return scipy.transpose(null_space)/null_space.sum()

In [248]:
s=solven(P-I)
s

array([[ 0.25 ],
       [ 0.375],
       [ 0.375]])

In [241]:
s

array([[ 0.25 ],
       [ 0.375],
       [ 0.375]])

In [242]:
s=s/s.sum()
s

array([[ 0.25 ],
       [ 0.375],
       [ 0.375]])

In [226]:
np.dot(P,s)

array([[ 0.25 ],
       [ 0.375],
       [ 0.375]])

In [203]:
s

array([[ 0.25 ],
       [ 0.375],
       [ 0.375]])

In [204]:
3/8.0

0.375

In [251]:
5/8.00

0.625